{{- if .Values.narratorCredentials.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.narratorCredentials.secretName }}
type: Opaque
stringData:
  username: {{ .Values.narratorCredentials.username | quote }}
  password: {{ .Values.narratorCredentials.password | quote }}
{{- end }}
