{
  "apiVersion": "kafka.strimzi.io/v1",
  "kind": "KafkaConnector",
  "metadata": {
    "name": "plate-waste-source-connector",
    "namespace": "kafka",
    "labels": {
      "strimzi.io/cluster": "connect-cluster"
    }
  },
  "spec": {
    "class": "org.apache.camel.kafkaconnector.mqttsource.CamelMqttsourceSourceConnector",
    "config": {
      "camel.kamelet.mqtt-source.brokerUrl": "ssl://mosquitto.kafka.svc.cluster.local:8883",
      "camel.kamelet.mqtt-source.clientId": "kafka-connect-plate-waste",
      "camel.kamelet.mqtt-source.topic": "sensors/plate-waste",
      "key.converter": "org.apache.kafka.connect.converters.ByteArrayConverter",
      "topics": "plate-waste-events",
      "value.converter": "org.apache.kafka.connect.converters.ByteArrayConverter"
    },
    "tasksMax": 1
  }
}
