apiVersion: kafka.strimzi.io/v1
kind: KafkaNodePool
metadata:
  name: dev-pool
  labels:
    strimzi.io/cluster: {{ .Values.clusterName }}
spec:
  replicas: {{ .Values.replicaCount }}
  roles:
    - controller
    - broker
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: 10Gi
        deleteClaim: false
  resources:
    requests:
      memory: 1Gi
      cpu: "250m"
    limits:
      memory: 2Gi
      cpu: "500m"
  jvmOptions:
    -Xms: 512m
    -Xmx: 1g
