apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: storage-consumer
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: storage-consumer
  template:
    metadata:
      labels:
        app.kubernetes.io/name: storage-consumer
    spec:
      containers:
        - name: storage-consumer
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: {{ .Values.kafka.bootstrapServers | quote }}
            - name: KAFKA_CONSUMER_GROUP
              value: {{ .Values.kafka.consumerGroup | quote }}
            - name: TIMESCALE_DSN
              value: >-
                postgresql://$(DB_USER):$(DB_PASSWORD)@{{ .Values.timescaledb.host }}:{{ .Values.timescaledb.port }}/{{ .Values.timescaledb.database }}
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.timescaledb.existingSecret }}
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.timescaledb.existingSecret }}
                  key: password
          resources:
{{ toYaml .Values.resources | indent 12 }}
