{{- if .Values.credentials.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.credentials.secretName }}
type: Opaque
stringData:
  root-user: {{ .Values.credentials.rootUser | quote }}
  root-password: {{ .Values.credentials.rootPassword | quote }}
{{- end }}
